import { Link } from "react-router-dom";
import { IpTrademarksSection } from "@/components/IpTrademarksSection";

export default function Privacy() {
  return (
    <main className="min-h-screen bg-background text-foreground px-6 py-16">
      <article className="prose prose-invert max-w-3xl mx-auto">
        <Link to="/" className="text-sm text-muted-foreground hover:text-foreground">← Back</Link>
        <h1 className="text-4xl font-bold text-gradient-emerald mt-4 mb-2">Privacy Notice</h1>
        <p className="text-sm text-muted-foreground">Last updated: May 2, 2026</p>

        <h2 className="mt-8">Who we are</h2>
        <p><strong>PGVA Ventures© LLC</strong> (Dulles, Virginia, USA), trading as Unicorn AI Builder™ / Unicorn Holdings, is the data controller for personal data processed through this service.</p>

        <h2>What we collect</h2>
        <ul>
          <li><strong>Account data</strong>: name, email, login credentials, display name.</li>
          <li><strong>Usage data</strong>: prompts you submit, AI responses, feature usage, session and device identifiers, IP address, log data.</li>
          <li><strong>Support data</strong>: messages and attachments you send to our support.</li>
        </ul>
        <p>Payment data (card details, billing address) is collected and processed directly by our Merchant of Record, <strong>Paddle</strong>, not by us.</p>

        <h2>Why we use it (legal basis)</h2>
        <ul>
          <li><strong>Contract performance</strong>: to create your account, deliver the service, and process subscriptions.</li>
          <li><strong>Legitimate interests</strong>: security and fraud prevention, product improvement, internal analytics.</li>
          <li><strong>Consent</strong>: marketing emails (where required) and non-essential cookies.</li>
          <li><strong>Legal obligation</strong>: tax, accounting, and responding to lawful requests.</li>
        </ul>

        <h2>Who we share with</h2>
        <ul>
          <li><strong>Subprocessors</strong>: cloud hosting (Supabase), AI inference providers (OpenAI, Google, Anthropic via Lovable AI Gateway), analytics, email delivery, customer support tooling.</li>
          <li><strong>Merchant of Record</strong>: Paddle, for sale of subscriptions, payments, tax compliance, invoicing and refunds.</li>
          <li><strong>Professional advisers</strong>: legal and accounting where necessary.</li>
          <li><strong>Authorities</strong>: where required by law.</li>
        </ul>

        <h2>How long we keep it</h2>
        <p>We keep account and usage data for as long as your account is active and for a reasonable period afterwards (typically up to 24 months) for legal, accounting and dispute-resolution purposes, after which it is deleted or anonymised.</p>

        <h2>Your rights</h2>
        <p>Subject to applicable law (including the CCPA for California residents and GDPR for UK/EEA residents), you may request access, correction, deletion, restriction, portability, or objection regarding your personal data, and you may withdraw consent at any time. UK/EEA users also have the right to lodge a complaint with their supervisory authority. We will respond within 30 days.</p>

        <h2>International transfers</h2>
        <p>We are based in the United States. If you access the service from outside the US, your data will be transferred to and processed in the US. Where required, we rely on standard contractual safeguards.</p>

        <h2>Security</h2>
        <p>We use industry-standard technical and organisational measures including encryption in transit, access controls, and audit logging to protect your data.</p>

        <h2>Cookies</h2>
        <p>We use essential cookies to keep you signed in and secure the service, plus limited analytics cookies to understand usage. You can manage cookie preferences in your browser.</p>

        <IpTrademarksSection />

        <h2>Children's privacy</h2>
        <p>The service is not directed to children under 13 (or 16 in the UK/EEA), and we do not knowingly collect personal data from them. If you believe a child has provided us data, contact us and we will delete it.</p>

        <h2>Automated decision-making &amp; AI training</h2>
        <p>AI outputs are generated by third-party large-language models routed through Lovable AI Gateway. <strong>We do not sell your personal data.</strong> We do not use your prompts or outputs to train third-party foundation models. We may use de-identified, aggregated usage data to improve our own routing, safety, and product quality.</p>

        <h2>Data breach notification</h2>
        <p>In the event of a personal-data breach likely to result in risk to your rights, we will notify affected users and, where required, the relevant supervisory authority within 72 hours of discovery, in accordance with applicable law (GDPR Art. 33–34, US state breach-notification statutes).</p>

        <h2>Do Not Track &amp; Global Privacy Control</h2>
        <p>We honor the Global Privacy Control (GPC) signal as a valid opt-out of the "sale" or "sharing" of personal information for California residents.</p>

        <h2>DMCA &amp; legal contact</h2>
        <p>Copyright complaints: <em>dmca@pgvaventures.com</em>. Privacy requests: <em>privacy@pgvaventures.com</em>. Legal notices: <em>legal@pgvaventures.com</em>.</p>

        <h2>Contact</h2>
        <p>PGVA Ventures© LLC, Dulles, Virginia, USA. For privacy requests, email <em>privacy@pgvaventures.com</em> or use in-app support channels.</p>

        <p className="mt-8"><Link to="/terms">Terms</Link> · <Link to="/refund">Refund Policy</Link></p>
      </article>
    </main>
  );
}
